name: Test
on:
  push:
    branches:
      - master
      - backend
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.8
      - name: Install Python dependencies
        run: |
          mv backend app
          mkdir backend
          mv app backend
          cd backend/app
          pip install -r requirements.txt
      - name: Run test
      - name: run test
        run: |
          cd backend/app
          pytest
